name: docker
on:
  push:
    tags: [ "*.*.*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: docker/login-action@v1
      with:
        username: neowu
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        file: "ext/docker/log-collector/Dockerfile"
        push: true
        tags: "neowu/log-collector:${{ env.TAG }}"
