name: jre
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        username: neowu
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - run: ls -l .
    - uses: docker/build-push-action@v2
      with:
        context: "./docker/jre"
        tags: "neowu/jre:17"
        push: true
